server:
 port: 8081

spring:
 application:
  name: PaymentService
 config:
  import: configserver:http://localhost:9296
 datasource:
  url: jdbc:mysql://localhost:3306/paymentdb
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update

management:
 tracing:
  sampling:
   probability: 1.0

#eureka:
# instance:
#  prefer-ip-address: true
# client:
#  register-with-eureka: true
#  fetch-registry: true  
#  service-url: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}